<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="G1C2ML14207" ignored="0" name="Default test" tests="7" failures="1" timestamp="17 Sep 2018 18:12:24 GMT" time="78.942" errors="0">
  <testcase name="Test_Case1_CheckTitle" time="8.638" classname="com.mindtree.omsframework.testcasesExecution.OMS_Homepage_Test">
    <failure type="java.lang.AssertionError" message="expected [OMS-QA-1.8.0] but found [OMS-QA-1.8]">
      <![CDATA[java.lang.AssertionError: expected [OMS-QA-1.8.0] but found [OMS-QA-1.8]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.mindtree.omsframework.testcasesExecution.OMS_Homepage_Test.Test_Case1_CheckTitle(OMS_Homepage_Test.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Test_Case1_CheckTitle -->
  <testcase name="Test_Case2_checkomsTitle" time="0.121" classname="com.mindtree.omsframework.testcasesExecution.OMS_Homepage_Test"/>
  <testcase name="TestCase_Batch_Button_OMS" time="0.238" classname="com.mindtree.omsframework.testcasesExecution.OMS_Homepage_Test"/>
  <testcase name="TestCase_Track_Button_OMS" time="0.197" classname="com.mindtree.omsframework.testcasesExecution.OMS_Homepage_Test"/>
  <testcase name="TestCase_Assginment_Button_OMS" time="0.226" classname="com.mindtree.omsframework.testcasesExecution.OMS_Homepage_Test"/>
  <testcase name="TestCase_Groups_Button_OMS" time="0.215" classname="com.mindtree.omsframework.testcasesExecution.OMS_Homepage_Test"/>
  <testcase name="TestCase_Users_Button_OMS" time="0.169" classname="com.mindtree.omsframework.testcasesExecution.OMS_Homepage_Test"/>
</testsuite> <!-- Default test -->
